src/Entity/TokenNumber.php
<?php

namespace App\Entity;

use App\Repository\TokenNumberRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TokenNumberRepository::class)
 */
class TokenNumber
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $number;

    /**
     * @ORM\Column(type="string", length=10, nullable=true)
     */
    private $result;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $location;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $UpdateAt;

    /**
     * @ORM\Column(type="boolean")
     */
    private $hasSee = false;

    /**
     * @ORM\ManyToOne(targetEntity=User::class)
     */
    private $testedBy;

    /**
     * @ORM\Column(type="boolean")
     */
    private $active = false;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $seeAt;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isUsed = false;

    /**
     * @ORM\ManyToOne(targetEntity=User::class)
     */
    private $activateBy;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $testedAt;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumber(): ?int
    {
        return $this->number;
    }

    public function setNumber(int $number): self
    {
        $this->number = $number;

        return $this;
    }

    public function getResult(): ?string
    {
        return $this->result;
    }

    public function setResult(?string $result): self
    {
        $this->result = $result;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(string $location): self
    {
        $this->location = $location;

        return $this;
    }

    public function getUpdateAt(): ?\DateTimeInterface
    {
        return $this->UpdateAt;
    }

    public function setUpdateAt(\DateTimeInterface $UpdateAt): self
    {
        $this->UpdateAt = $UpdateAt;

        return $this;
    }

    public function getHasSee(): ?bool
    {
        return $this->hasSee;
    }

    public function setHasSee(bool $hasSee): self
    {
        $this->hasSee = $hasSee;

        return $this;
    }

    public function getTestedBy(): ?User
    {
        return $this->testedBy;
    }

    public function setTestedBy(?User $testedBy): self
    {
        $this->testedBy = $testedBy;

        return $this;
    }

    public function getActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(bool $active): self
    {
        $this->active = $active;

        return $this;
    }

    public function getSeeAt(): ?\DateTimeInterface
    {
        return $this->seeAt;
    }

    public function setSeeAt(?\DateTimeInterface $seeAt): self
    {
        $this->seeAt = $seeAt;

        return $this;
    }

    public function getIsUsed(): ?bool
    {
        return $this->isUsed;
    }

    public function setIsUsed(bool $isUsed): self
    {
        $this->isUsed = $isUsed;

        return $this;
    }

    public function getSerializeToken()
    {
        return [
            "id" => $this->id,
            "number" => $this->number,
            "result" => $this->result,
            "location" => $this->location,
            'ActivateAt' =>$this->UpdateAt ? $this->UpdateAt->format("Y-D-M h:m:s") : null,
            "ActivateBy" => $this->activateBy ? [
                "id" => $this->testedBy->getId(),
                "email" => $this->testedBy->getEmail(),
                "userName" => $this->testedBy->getUsername()
            ] : [],
            "testedBy" => $this->testedBy ? [
                "id" => $this->testedBy->getId(),
                "email" => $this->testedBy->getEmail(),
                "userName" => $this->testedBy->getUsername()
            ] : [],
            "testedAt" => $this->testedAt ? $this->testedAt->format("Y-D-M h:m:s") : null,
            "hasSee" => $this->hasSee,
            "seeAt" => $this->seeAt ? $this->seeAt->format("Y-D-M h:m:s") : null
        ];
    }

    public function getActivateBy(): ?User
    {
        return $this->activateBy;
    }

    public function setActivateBy(?User $activateBy): self
    {
        $this->activateBy = $activateBy;

        return $this;
    }

    public function getTestedAt(): ?\DateTimeInterface
    {
        return $this->testedAt;
    }

    public function setTestedAt(?\DateTimeInterface $testedAt): self
    {
        $this->testedAt = $testedAt;

        return $this;
    }
}

src/Controller/ResultController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\TokenNumber;
use Symfony\Component\HttpFoundation\Response;
/**
* @Route("/result", name="result")
*/
class ResultController extends AbstractController
{
    /**
     * @Route("", name="Get_result")
     */
    public function get_result()
    {
        return $this->render('result/index.html.twig', [
            'controller_name' => 'ResultController',
        ]);
    }
    /**
     * @Route("/{id}", name="Show_result")
     */
    public function show_result($id)
    {
        $resRep = $this->get("doctrine")->getRepository(TokenNumber::class);
        $result = $resRep->findOneBy(["number" => (int) $id, "active" => true]);
        if ($result instanceof TokenNumber)
        {
            $result->setHasSee(true);
            $result->setSeeAt(new \DateTime('now'));
            return $this->render('result/index.html.twig', [
                'card' => $result,
            ]);
        }
        else
        {
            return $this->render('result/index.html.twig', [
                'errors' => 'Numéro non définie', "card" => ["number" => $id]]);
        }
    }
}

templates/result/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Resultat{% endblock %}

{% block body %}
<style>
    .example-wrapper {font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
    .kotitle { margin-left: 36% }
</style>

<div class="example-wrapper container-small">
    <h2 class="kotitle"> Consultation du resultat</h2>
    {% if errors is defined %}
        <div style="margin-left: 20%; margin-right: 20%; text-align:center; font-size: 150%" class="alert alert-danger" role="alert">
            <p> {{ errors }} </p>
        </div>
    {% endif %}
    <div style="margin-left: 35%">
    {% if card is defined %}
    <input  class="btn btn-primary" style="font-size: 150%" type="button" value="Scan par numero de la carte" id="result_by_number" hidden />
    <input class="btn btn-primary" style="font-size: 150%" type="button" value="Scan par camera de la carte" id="result_by_scan"/>
    </div>
    </br>
    <div id="scanResult" hidden>
    {% else %}
    <input class="btn btn-primary" style="font-size: 150%" type="button" value="Scan par numero de la carte" id="result_by_number"/>
    <input  class="btn btn-primary" style="font-size: 150%" type="button" value="Scan par camera de la carte" id="result_by_scan" hidden/>
    </div>
    </br>
    <div id="scanResult">
    {% endif %}
        <div>
            <canvas id="canvasElement"></canvas>
            <video id="lectorElement" width="100%" height="100%" hidden>
            </video>
        </div>
        <p id="cameraError" hidden>Camréa introuvable merci de recharger la page ou d'activer votre caméra dans les options du navigateur.</p>
    </div>

    {% if card is defined %}
        <div id="numberResutl" style="font-size: 200%">
    {% else %}
        <div id="numberResutl"  style="font-size: 200%" hidden>
    {% endif %}
        <form id="formSend" style=" margin-left: 21%; margin-right: 21%">
            <div class="form-group">
                <label for="cardNumber">Numéro de la carte</label>
                {% if card.number is defined and card.number | length > 0 %}
                    <input type="text" class="form-control" style="size: 150%" name="cardNumber" id="cardNumber" aria-describedby="cardNumberlHelp" value={{card.number}} />
                {% else %}
                    <input type="text" class="form-control" style="font-size: 150%" name="cardNumber" id="cardNumber" aria-describedby="cardNumberlHelp" placeholder="xxxxxxxx" />
                {% endif %}
                <small id="cardNumberHelp" class="form-text text-muted">Numéro a 8 chiffre inscrit sur la Carte xxxx-xxxx</small>
            </div>
            <button style="font-size: 100%" type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>


    {% if card is defined %}
	</br>
	<div class="alert alert-success" style="margin-left: 30%; margin-right:30%;font-size:150%">
        {% if card.result is defined and card.result == "yes" %}
            <p style="color: red;" id="testResult">Résultat positif</p>
        {% elseif card.result is defined and  card.result == "no" %}
            <p id="testResult">Résultat négatif</p>
       {% elseif card.result is defined and  card.result == "undefined" %}
            <p id="testResult">Le test n'a pas été concluant.</p>
            <br>
            <p>Nous vous invitons a proceder a un autre test.</p>
        {% else %}
            <p>Résultat indisponible pour le moment</p>
        {% endif %}
        {% if card.result is defined %}
            <p id="testDate">Fait le {{ card.updateAt|date('d-m-Y H:m') }}</p>
            <p id="testLocation">a {{ card.location }}</p>
            <input type="button" value="exporter au format PDF" id="exportAsPDF" class="btn btn-primary" style="font-size: 100%;" />
        {% endif %}
	</div>
    {% endif %}
</div>

<img id="mainLogo" src="../assets/logo_citi.png"  hidden/>
{% endblock %}
{% block javascripts %}
<script type="module">
    import QrScanner from "../assets/scripts/qr-scanner.js";
    QrScanner.WORKER_PATH = '../assets/scripts/qr-scanner-worker.min.js';
    let lectorElem = document.getElementById("lectorElement");
    if (detectMob() === true)
    {
        lectorElem.width = Math.round((window.screen.width * 250) / 100);
        lectorElem.height = Math.round((window.screen.height * 180) / 100);
    }
    else
    {
        lectorElem.width = Math.round((window.screen.width * 50) / 100);
        lectorElem.height = Math.round((window.screen.height * 50) / 100);
    }
    let form = document.getElementById("formSend");
    let formsT = [
            {id: "result_by_number", target: "numberResutl", actionStart: null, actionStop: null},
            {id: "result_by_scan", target: "scanResult", actionStart: startLector, actionStop: stopLector}
        ];
    let canElem = document.getElementById("canvasElement");
    let qrcode = new QrCodeView(canElem, lectorElem);
    let qrScanner = new QrScanner(lectorElem, scanSuccess);
    let cameraErrorElem = document.getElementById("cameraError");

    if (document.getElementById("exportAsPDF"))
    {
        document.getElementById("exportAsPDF").onclick = exportAsPdf;
    }
    lectorElem.addEventListener("play", function ()
    {
        let self = this;
        (function loop()
        {
            if (!self.paused && !self.ended)
            {
                qrcode.startDraw();
                setTimeout(loop, 1000 / 30);
            }
        })();
    });

    form.onsubmit = sendForm;
    init();
    if (document.getElementById("scanResult").hidden === false)
        startLector();
    function startLector()
    {
        qrScanner.start().then(
            () => {
                if (cameraErrorElem.hidden === false)
                {
                    cameraErrorElem.hidden = true;
                    changeScan({target: {id: "result_by_number"}})
                }
            }
        ).catch(() =>{
            cameraErrorElem.hidden = false;
            changeScan({target: {id: "result_by_number"}});
        });
    }

    function stopLector()
    {
        qrScanner.pause();
    }
    function exportAsPdf()
    {
        let file = new jsPDF();
        let coordonate = [10, 10];
        let tinfo = ["Result", "Date", "Location"];
        let result = document.getElementById("testResult").innerText;
        let date = document.getElementById("testDate").innerText;
        let location = document.getElementById("testLocation").innerText;
        let numero = window.location.href.split("/");
        numero = numero[numero.length - 1];
        file.addImage(document.getElementById("mainLogo"), "PNG", 10, 10);
        file.text("Le test numero " + numero, 10, 80);
	file.text("Resultat: " + result, 10, 90);
        file.text(date, 10, 100);
        file.text(location, 10, 110);
        file.save("test.pdf");
    }

    function scanSuccess(result)
    {
        qrScanner.destroy();
        let tmp = result.split('/');
        window.location.replace(defaultaddr + "/result/" + tmp[tmp.length - 1]);
    }

    function changeScan(event)
    {
        let c = -1;
        while (formsT[++c])
        {
            if (formsT[c].id === event.target.id)
            {
                document.getElementById(formsT[c].target).hidden = false;
                document.getElementById(formsT[c].id).hidden = true;
                if (formsT[c].actionStart !== null)
                    formsT[c].actionStart();
            }
            else
            {
                document.getElementById(formsT[c].id).hidden = false;
                document.getElementById(formsT[c].target).hidden = true;
                if (formsT[c].actionStop !== null)
                    formsT[c].actionStop();
            }
        }
    }

    function sendForm(event)
    {
        event.preventDefault();
        let number = event.target[0].value;
        let tmp = event.target.action.split('/');
        if (parseInt(tmp[tmp.length - 1]) > 0)
            tmp.pop();
        if (tmp[tmp.length - 1] === "")
            tmp[tmp.length - 1] = "result";
        window.location = tmp.join("/") + "/" + number;

    }

    function init()
    {
        let c = -1;
        while (formsT[++c])
        {
            document.getElementById(formsT[c].id).onclick = changeScan;
        }
    }
    function detectMob() {
        return toMatch.some((toMatchItem) => {
            return navigator.userAgent.match(toMatchItem);
        });
    }
</script>
{% endblock %}